### ISSUE TITLE
Tracking: SciPy Proceedings

### ISSUE THREAD

**Issue by rowanc1** [jupyter-book/mystmd#1009]
Curvenote is sponsoring the 2024 conference proceedings for SciPy, as detailed in [this announcement](https://curvenote.one/news/curvenote-sponsors-scipy-proceedings-2024) which will be using MyST for their build process, there are two modes (1) MyST Markdown; and (2) LaTeX. The instructions will be updated to point people to install the tool and run locally, and github actions have been made to run the build process in GitHub actions.

The current scipy proceedings site built with myst and Curvenote can be found here:
https://proceedings.scipy.org

There are a number of improvements that we need to make to make the install, documentation and theme process easier:

## Documentation

- [x] Document latex --> myst #1007 
- [ ] Document on how to start with RST and what tools to use when upgrading to MyST

## LaTeX Features

- [x] `longtable*` and `longtable` parsing #1041
- [x] `eqnarray*`
- [x] numbered code environments (maybe just point them to use markdown in this case) #1054

## Mini Features/Bugs

- [x] #1021
- [x] `copyright` holder - this can be defaulted to the authors name e.g. `Authors et. al` - #1035
- [x] `Could not find static resource at "main.pdf". See 'config.site.actions'` -- The theme crashes if static actions are not found, this should be made permissive. #1048 #1049
- [ ] Link to a PDF on github breaks the preview https://github.com/eeg-to-fmri/eeg-to-fmri/blob/main/project_UML.pdf

## Theme Updates

- [x] Numbered references in theme
- [ ] `Fig. 1` etc.
- [x] Footnotes on page (link to theme issue!) #926

## New Functionality

- [x] Acknowledgements section tagged properly #508
- [x] List editors and reviewers #1036
- [x] Ability to have a collaboration as an author? #1038
- [x] We need some way to specify downloads for an article, with title and an ID to an export. These can be listed by the theme. #1049

**Comment by LecrisUT** [comment]
> Ability to have a collaboration as an author?

How about having several modes:
- filter-orcid: only contributors who made their orcid public in github (gitlab?) profile are included with their orcid and extracted affiliations. Reasoning is, if they went through the trouble of making it public, maybe they want it to be used.
- all: get any and all contributors, with the github profile name+affiliation if orcid is not present.

**Comment by rowanc1** [comment]
@LecrisUT -- thanks for the comment! I was a bit terse with my feature requests by "having a collaboration as an author" I meant that an entity like "The MyST Project" can be listed as an author. This needs slightly different parsing (e.g. for the name (last name/ first name are not applicable)) which makes the collaboration look more like an affiliation. All contributors can also be listed, although I don't think we are pulling those up anywhere in the themes/templates at this point.
