### ISSUE TITLE
SciPy 2024 Sprint Planning

### ISSUE THREAD

**Issue by rowanc1** [jupyter-book/mystmd#1379]
## For the "MyST Curious" and general project onboarding

- [ ] Any one who has a JupyterBook (come and talk to us and we will get you up and running and answer any questions)
- [ ] Onboard and teach any contributors
- [ ] Project Pythia (landing pages, footer)
- [ ] SciPy Proceedings (documentation on how to upgrade an article (video @fwkoch)), transfer the archive from Curvenote, document where we are at

## Integration

- [ ] AnyWidget
- [ ] Pyvista
- [ ] ITK
- [ ] Notebook widget state
- [ ] Rmd / Quarto / pandoc syntax (Playing nice track from scipy)
- [ ] sphinx auto doc

## Development / Core Features

- [ ] Go over and define roadmap together for next two years!
- [ ] Continuous numbering
- [ ] JupyterBook v2 is deployed on NPM
- [ ] Remix v2 + Vite
- [ ] hydrate widgets from notebook metadata state
- [ ] https://github.com/executablebooks/mystmd/issues/1373
- [ ] External resource file support, with exclude large files from build
- [ ] https://github.com/executablebooks/mystmd/issues/670

## Features

- [ ] sub figure placements (for scipy!) https://github.com/executablebooks/mystmd/issues/1352
- [ ] alt-text on outputs (for @lwasser)
- [ ] markup syntax for @stefanv
- [ ] landing pages theme
- [ ] sphinx
- [ ] markdown export (myst/gh/pandoc etc)
- [x] #1170
- [x] #1388
- [x] #1387
- [x]  #1387
- [x] #1222
- [x] #1369
- [x] #1390

## Documentation

- [ ] Jupyter book v2 docs are deployed
- [ ] Landing page and ecosystem pages on mystmd are reimagined
- [ ] Pass on compass and contributing

## Joining project Jupyter

- [x] Move mystmd
- [x] Move mystmd.org
- [ ] Update footers on mystmd.org
- [ ] get a blog up, write one about scipy

## Syntax Improvements / Discussions

- [ ] Div fences
- [ ] Spans (ala djot)

## Bug Hunting

- [ ] https://github.com/executablebooks/mystmd/issues/1357

**Comment by rowanc1** [comment]
@manzt and @stevejpurves have integrated anywidget and MyST!

![image](https://github.com/user-attachments/assets/338a4cad-30a0-4fb2-93ae-74183baedf91)

**Comment by rowanc1** [comment]
@agoose77 has gotten a first pass on documentation reading from Sphinx autodoc!

![image](https://github.com/user-attachments/assets/269aa38a-66a8-4b3f-a5a9-02cc7c4431a5)

**Comment by agoose77** [comment]
@rowanc1 I'm closing this as a tracking issue that's past-tense :)
